// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtgyYhQiN_QhVVwyk62Ehqgz1SmkWB-s4',
    appId: '1:96197216860:web:8cad454099b43025957499',
    messagingSenderId: '96197216860',
    projectId: 'movies-app-4ccfe',
    authDomain: 'movies-app-4ccfe.firebaseapp.com',
    storageBucket: 'movies-app-4ccfe.firebasestorage.app',
    measurementId: 'G-BJYDN1QESV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC01VMXzKJagPh2_imlyzTPJw_F1EpciLE',
    appId: '1:96197216860:android:6697c000a997f8b8957499',
    messagingSenderId: '96197216860',
    projectId: 'movies-app-4ccfe',
    storageBucket: 'movies-app-4ccfe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpUvJEi_whVsB-0r7TLaSgN4Mz9vwCiJo',
    appId: '1:96197216860:ios:5a9572e863b79b20957499',
    messagingSenderId: '96197216860',
    projectId: 'movies-app-4ccfe',
    storageBucket: 'movies-app-4ccfe.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
